### ISSUE TITLE
Simple form

### ISSUE THREAD

**Issue by Zaid0307** [Zaid0307/capstone-project#1]
## Value Preposition

**As a User** User
**I need**  to fill in my Workout data
**to be able to**  document my workout

## Description
<img src="https://user-images.githubusercontent.com/98756693/159951005-07ec604a-ac09-4d35-aac2-31139e7b8245.png" width="300">

## Acceptance Criteria

- [ ] Create seven input fields to enter Workout data
- [ ] When click the "Create" button, the data is displayed below the button

## Tasks

- [ ] Create a branch `simple-form`
- [ ] Create component "simple-form" and stories.js, spec.js
- [ ] Create Button component and stories.js, spec.js
- [ ] all input fields are required
- [ ] maximum letters allowed in input: 20
- [ ] Add "create" button
