### ISSUE TITLE
Story 6 / 

### ISSUE THREAD

**Issue by Zaid0307** [Zaid0307/capstone-project#11]
## Value Preposition

**As a User** 
**I need**  an Button and a dropdown for the muscle input
**to be able to**  add more exercises / choose from 6 fixation options

## Description

<img src="https://user-images.githubusercontent.com/98756693/161938248-0c0f6afa-7427-4351-8326-aeab8c6f2a01.png" width="600">

## Acceptance Criteria

- [ ] After the button has been pressed, the entered entry will appear under the input fields

## Tasks

- [ ] create new branch `2ndFormButton`
- [ ] button must have `type='button'` 
- [ ] update test for  `DayForm`
- [ ] change the input field muscle to a doropdown
- [ ] Change input type from 'text' to 'number' for repetitions and sets
