### ISSUE TITLE
Story 7 / Save Workoutplan

### ISSUE THREAD

**Issue by Zaid0307** [Zaid0307/capstone-project#13]
## Value Preposition

**As a User** 
**I need**  save my workout plan 
**to be able to**  use it while working out

## Description

<img src="https://user-images.githubusercontent.com/98756693/162643253-b8a33dc0-42c0-4fee-b3b3-1619b0524d7e.png" width="600">

## Acceptance Criteria

- [ ] all added cards are saved and filed on a new page by workoutname, days, muscles and exercises 

## Tasks

- [ ] create new branch `savePlan`
- [ ] update onSubmit function
- [ ] modify code for storage function
