### ISSUE TITLE
Story 8 / Add muscle

### ISSUE THREAD

**Issue by Zaid0307** [Zaid0307/capstone-project#15]
## Value Preposition

**As a User** 
**I need**  i need to add more muscle per day 
**to be able to**  train several muscles every day

## Description

<img src="https://user-images.githubusercontent.com/98756693/162643776-2c351116-c6d3-4bd7-89a4-f5f517522696.png" width="600">

## Acceptance Criteria

- [ ] When clicking the Add Muscle button, a new Entry field appears in the Tag section.
- [ ] After clicking the "Save" button, the complete card will be saved and displayed on a new page.

## Tasks

- [ ] create new branch `addMuscle`
- [ ] update onSubmit function
- [ ] update `WorkoutPlan` Page
- [ ] modify code for storage function
