### ISSUE TITLE
Story 9 / Toggle Cards

### ISSUE THREAD

**Issue by Zaid0307** [Zaid0307/capstone-project#16]
## Value Preposition

**As a User** 
**I need** collapse my saved plans
**to be able to**   have a better overview of the individual sections in the plan 

## Description

<img src="https://user-images.githubusercontent.com/98756693/162644124-0a2f4656-3815-44e2-8003-c09d68527c05.png" width="600">

## Acceptance Criteria

- [ ] the sections "WorkoutPlanName", "Day" and "Muscel" get a button
- [ ] every time a Button is pressed, it collapses

## Tasks

- [ ] create new branch `ToggelCards`
- [ ] create toggel function 
- [ ] update `WorkoutPlan` Page
