### ISSUE TITLE
Story 10 / exercise overview

### ISSUE THREAD

**Issue by Zaid0307** [Zaid0307/capstone-project#17]
## Value Preposition

**As a User** 
**I need** to have a list of exercises
**to be able to**  have a choice of different exercises 

## Description

<img src="https://user-images.githubusercontent.com/98756693/162644886-ca8a2dac-092d-4107-8cba-c649df01315b.png" width="600">

## Acceptance Criteria

- [ ] The exercises are arranged according to the 6 most important muscle groups of the human body 
- [ ] when a button is pressed, exercises of the muscle groups are displayed 

## Tasks

- [ ] create new branch `exerciseOverview`
- [ ] create a new page with that name `exerciseOverview`
- [ ] add 6 buttons 
- [ ] Fetch API to get exercise data
- [ ] create `exerciseOverview.stories.js`
- [ ] create `exerciseOverview.spec.js`
