### ISSUE TITLE
Story 11 / detailed overview of the exercises

### ISSUE THREAD

**Issue by Zaid0307** [Zaid0307/capstone-project#18]
## Value Preposition

**As a User** 
**I need** a page with the complete description of the exercise 
**to be able to** read the descriptions of the exercises and see the pictures

## Description

<img src="https://user-images.githubusercontent.com/98756693/162645862-40f4d8d1-c1be-474e-a53c-8254cc760ac0.png" width="600">

## Acceptance Criteria

- [ ] when clicking on the preview card it appears a detailed overview 

## Tasks

- [ ] create new branch `exerciseDetailOverview`
- [ ] create a new page with that name `exerciseDetailOverview`
- [ ] fetch API to get exercise data
- [ ] create a layout card for the exerciseDetailOverview
