### ISSUE TITLE
Story 12 / add new exercise to overview

### ISSUE THREAD

**Issue by Zaid0307** [Zaid0307/capstone-project#19]
## Value Preposition

**As a User** 
**I need**  new form
**to be able to** add new exercises to the overview

## Description

<img src="(https://user-images.githubusercontent.com/98756693/162646042-9c833494-8358-4fba-b60c-1049b01be5da.png" width="600">

## Acceptance Criteria

- [ ] all input fields are required
- [ ] add images is optional
- [ ] maximum text length for the exercisename is 60 words
- [ ] the maximum text length for the description is 500 words
- [ ] created exercises appear in the overview for exercises

## Tasks

- [ ] create new branch `newExercise`
- [ ] create a new page with that name `CreateNewExercise`
- [ ] create `CreateNewExercise.storie.js`
- [ ] create `CreateNewExercise.spec.js`
- [ ] create a layout card for the exerciseDetailOverview
