### ISSUE TITLE
Simple form includes adding more exercise and new Card

### ISSUE THREAD

**Issue by Zaid0307** [Zaid0307/capstone-project#2]
## Value Preposition

**As a User** User
**I need**  two buttons one for adding more exercise and the other to add more Cards
**to be able to**  to make my Workout routine more efficient

## Description
<img src="https://user-images.githubusercontent.com/98756693/159734205-36e73a4e-9958-4cab-a5d3-e807e5a35615.png" width="300">

## Acceptance Criteria

- [ ] add a button to create more exercise
- [ ] add a button to create a new card

## Tasks

- [ ] create a new branch called `create-new-elements`
- [ ] update component and stories.js data
- [ ] update spec.js date
- [ ] When clicking on "add exercise", four new inputs are displayed
- [ ] When clicking on "Add workout card", a new card will be displayed
