### ISSUE TITLE
Simple form adding input for Days and Create button

### ISSUE THREAD

**Issue by Zaid0307** [Zaid0307/capstone-project#3]
## Value Preposition

**As a User** User
**I need** an extra input and a create button
**to be able to**  insert the days variably and to save my workout plan

## Description
<img src="https://user-images.githubusercontent.com/98756693/159756533-847b688d-f8a8-4bb8-be54-6c4a666a53c8.png" width="300">

## Acceptance Criteria

- [ ] swap static text with an input field 
- [ ] add a create button to save the Workoutplan

## Tasks

- [ ] create a new branch called `create-button-input-day`
- [ ] update component and stories.js data
- [ ] update spec.js date
- [ ] 
- [ ]
