### ISSUE TITLE
Story 4

### ISSUE THREAD

**Issue by Zaid0307** [Zaid0307/capstone-project#7]
## Value Preposition

**As a User** User
**I need** to add an new form 
**to be able to**  prepare my final form

## Description
<img src="https://user-images.githubusercontent.com/98756693/161520502-c37ec652-27f4-4deb-aada-fc1584159da3.png" width="300">

## Acceptance Criteria

- [ ] when I fill out the form, the data is stored in a useState
- [ ] CreateForm Page is toggled after pressing the Create button

## Tasks

- [ ] Create component `CreateForm`
- [ ] check in Safari, Chrome and Firefox Browser
