### ISSUE TITLE
Story 5 / Writing test and storybook data for CreateForm and WorkoutPlan component

### ISSUE THREAD

**Issue by Zaid0307** [Zaid0307/capstone-project#9]
## Value Preposition

**As a Developer** 
**I need**  to test my Components
**to be able to**  check if everything is working properly 

## Description

Writing test and storybook data

## Acceptance Criteria

- [ ] After creating 2 new components I still need to write the test and write the storybook file

## Tasks

- [ ] create new branch `Testing and Storybook`
- [ ] Write test for `CreateForm` and `WorkoutPlan`
- [ ] Write Storybook file for `CreateForm` and `WorkoutPlan`
